import type { Metadata } from "next";
import "./globals.css";
import { SITE_URL } from "@/lib/config";
import { PixelHead, PixelIntro } from "./pixel-motion";
import { PixelTransitions } from "./pixel-transitions";

const title = "Crate | Ready-made components for AI products.";
const description = "Ready-made UI components for AI products. Explore 12 wait states, install with one command, and make every small moment count.";
// 1200x630 share image, generated by scripts/og-image.mjs.
const shareImage = { url: "/og.png", width: 1200, height: 630, alt: "Crate: Your AI builds the product. Crate brings the UI." };

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: { url: "/apple-touch-icon.png", sizes: "180x180" },
  },
  manifest: "/manifest.webmanifest",
  title,
  description,
  openGraph: {
    title,
    description,
    type: "website",
    url: "/",
    siteName: "Crate",
    images: [shareImage],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: [shareImage],
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // suppressHydrationWarning: the head script marks <html data-intro> before React loads.
  return (
    <html lang="en" suppressHydrationWarning>
      <head><PixelHead /></head>
      <body><PixelIntro />{children}<PixelTransitions /></body>
    </html>
  );
}
