// Builds @onerollstudios/crate-elements: Crate's React components, unchanged,
// as custom elements (Preact's React-compatible runtime, shadow DOM).
//   1. Compiles the components' Tailwind classes into one stylesheet.
//   2. Generates each element's attributes, properties, and events from
//      ../lib/docs.generated.json, the same prop data as the docs and llms docs.
//   3. Bundles src/index.ts into dist/index.js with react aliased to preact/compat.
// Fails if the bundle grows past the size budget below.
// Run: npm run build (from crate/elements; run npm run build in crate/ first so
// the docs data is current).
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = fileURLToPath(new URL("..", import.meta.url));
const crateRoot = fileURLToPath(new URL("../..", import.meta.url));
const read = (path) => readFileSync(path, "utf8").replace(/\r\n?/g, "\n");

// Gzipped bytes the published bundle may use. Raise deliberately, never by accident.
const BUDGET = 22_000;

// Props named like global HTML attributes stay properties only, so for example
// Approval's title never doubles as the browser's tooltip.
const GLOBAL_ATTRIBUTES = new Set(["title", "hidden", "id", "lang", "dir", "slot", "part", "style", "class"]);

// Callback props become DOM events that bubble out of the shadow root.
const EVENTS = { onRetry: "crate-retry", onCancel: "crate-cancel", onAllow: "crate-approve", onDeny: "crate-deny" };

// ---------- 1. CSS ----------
mkdirSync(`${root}build`, { recursive: true });
execFileSync(process.execPath, [`${root}node_modules/@tailwindcss/cli/dist/index.mjs`, "-i", `${root}src/styles.css`, "-o", `${root}build/styles.css`, "--minify"], { cwd: root, stdio: "pipe" });
const compiled = read(`${root}build/styles.css`);
// @property rules have no effect inside a shadow root, so they are registered
// once on the document instead (src/styles-runtime.ts).
const properties = (compiled.match(/@property\s*--[\w-]+\s*\{[^}]*\}/g) ?? []).join("");
const styles = compiled.replace(/@property\s*--[\w-]+\s*\{[^}]*\}/g, "");

// ---------- 2. Element specs ----------
const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const docs = JSON.parse(read(`${crateRoot}lib/docs.generated.json`));
const problems = [];
const specs = docs.filter((doc) => doc.playground).map((doc) => {
  const attributes = [];
  const properties = [];
  const events = {};
  // Required list props (Sources' sources, AgentPlan's steps) start empty, so an
  // element renders before the page sets them instead of throwing.
  const defaults = {};
  for (const prop of doc.playground) {
    if (!prop.optional && prop.type.endsWith("[]")) defaults[prop.name] = [];
    if (prop.name === "className") continue;
    if (prop.type.includes("=>")) {
      if (!EVENTS[prop.name]) problems.push(`${doc.name}: no event name for ${prop.name}`);
      else events[prop.name] = EVENTS[prop.name];
      continue;
    }
    const kind = prop.literals || prop.type === "string" ? "string" : prop.type === "number" ? "number" : prop.type === "boolean" ? "boolean" : null;
    if (kind && !GLOBAL_ATTRIBUTES.has(prop.name)) attributes.push({ name: kebab(prop.name), prop: prop.name, kind });
    properties.push(prop.name);
  }
  return { tag: `crate-${doc.name}`, component: doc.title, attributes, properties, events, defaults };
});
if (problems.length) {
  console.error(`crate-elements: cannot build:\n- ${problems.join("\n- ")}`);
  process.exit(1);
}
mkdirSync(`${root}src/generated`, { recursive: true });
writeFileSync(`${root}src/generated/specs.ts`, `// Generated by scripts/build.mjs from crate/lib/docs.generated.json. Do not edit.\nimport type { ElementSpec } from "../element";\n\nexport const specs: ElementSpec[] = ${JSON.stringify(specs, null, 2)};\n`);
writeFileSync(`${root}src/generated/styles.ts`, `// Generated by scripts/build.mjs from src/styles.css. Do not edit.\nexport const styles = ${JSON.stringify(styles)};\nexport const properties = ${JSON.stringify(properties)};\n`);

// ---------- 3. Bundle ----------
rmSync(`${root}dist`, { recursive: true, force: true });
const preact = (path) => `${root}node_modules/preact/${path}`;
await build({
  entryPoints: [`${root}src/index.ts`],
  outfile: `${root}dist/index.js`,
  bundle: true,
  minify: true,
  format: "esm",
  target: "es2020",
  jsx: "automatic",
  legalComments: "none",
  tsconfig: `${crateRoot}tsconfig.json`,
  alias: {
    react: preact("compat/dist/compat.module.js"),
    "react-dom": preact("compat/dist/compat.module.js"),
    "react/jsx-runtime": preact("jsx-runtime/dist/jsxRuntime.module.js"),
  },
  logLevel: "error",
});

// The CSS ships inside the bundle, so one number covers both.
const js = gzipSync(readFileSync(`${root}dist/index.js`)).length;
const css = gzipSync(styles + properties).length;
console.log(`crate-elements: ${specs.length} elements; dist/index.js ${(readFileSync(`${root}dist/index.js`).length / 1024).toFixed(1)} KB, ${(js / 1024).toFixed(1)} KB gzip (of which CSS about ${(css / 1024).toFixed(1)} KB gzip)`);
if (js > BUDGET) {
  console.error(`crate-elements: dist/index.js is ${js} bytes gzip, over the ${BUDGET} byte budget`);
  process.exit(1);
}
